import { z } from 'zod';
import {
  getEnabledAirportIds,
  ALLOW_OTHER_AIRPORT,
  OTHER_AIRPORT_ID,
  VEHICLE_PREFERENCE_VALUES,
} from '@/config/airports';

export const bookingSchema = z.object({
  customerName: z.string().min(2, 'Name must be at least 2 characters').max(100),
  customerEmail: z.string().email('Invalid email address'),
  customerPhone: z.string().min(10, 'Phone number must be at least 10 digits').max(20),
  customerWhatsApp: z.string().min(10, 'WhatsApp number must be at least 10 digits').max(20).optional().or(z.literal('')),
  vehicleId: z.string().min(1, 'Please select a vehicle'),
  rentalType: z.enum(['SELF_DRIVE', 'CHAUFFEUR', 'AIRPORT_TRANSFER', 'CORPORATE', 'OTHER']),
  pickupLocation: z.string().min(2, 'Pickup location is required').max(200),
  dropoffLocation: z.string().min(2, 'Drop-off location is required').max(200),
  pickupDate: z.string().min(1, 'Pickup date is required'),
  pickupTime: z.string().min(1, 'Pickup time is required'),
  returnDate: z.string().min(1, 'Return date is required'),
  returnTime: z.string().min(1, 'Return time is required'),
  flightNumber: z.string().max(50).optional().or(z.literal('')),
  passengers: z.coerce.number().min(1, 'At least 1 passenger').max(50),
  luggage: z.coerce.number().min(0).max(20).optional(),
  specialRequests: z.string().max(1000).optional().or(z.literal('')),
  /**
   * Idempotency key for duplicate submission protection. Generated by the
   * form (one per submission attempt) and enforced by the unique constraint
   * on `Booking.submissionId` - the server-side check never trusts the client.
   */
  submissionId: z.string().uuid('Invalid submission id').optional().or(z.literal('')),
  honeypot: z.string().optional(),
}).refine((data) => {
  const pickup = new Date(`${data.pickupDate}T${data.pickupTime}`);
  const returnDate = new Date(`${data.returnDate}T${data.returnTime}`);
  return returnDate > pickup;
}, {
  message: 'Return date/time must be after pickup date/time',
  path: ['returnDate'],
}).refine((data) => {
  const pickup = new Date(`${data.pickupDate}T${data.pickupTime}`);
  return pickup > new Date();
}, {
  message: 'Pickup date/time must be in the future',
  path: ['pickupDate'],
}).refine((data) => !data.honeypot, {
  message: 'Spam detected',
  path: ['honeypot'],
});

export const contactSchema = z.object({
  name: z.string().min(2, 'Name must be at least 2 characters').max(100),
  email: z.string().email('Invalid email address'),
  phone: z.string().min(10, 'Phone number must be at least 10 digits').max(20),
  subject: z.string().min(2, 'Subject is required').max(200),
  message: z.string().min(10, 'Message must be at least 10 characters').max(2000),
  honeypot: z.string().optional(),
}).refine((data) => !data.honeypot, {
  message: 'Spam detected',
  path: ['honeypot'],
});

export const inquirySchema = z.object({
  name: z.string().min(2, 'Name must be at least 2 characters').max(100),
  email: z.string().email('Invalid email address'),
  phone: z.string().min(10, 'Phone number must be at least 10 digits').max(20),
  subject: z.string().min(2, 'Subject is required').max(200),
  message: z.string().min(10, 'Message must be at least 10 characters').max(2000),
  honeypot: z.string().optional(),
}).refine((data) => !data.honeypot, {
  message: 'Spam detected',
  path: ['honeypot'],
});

const DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;
const TIME_PATTERN = /^([01]\d|2[0-3]):[0-5]\d$/;

/**
 * Airport-transfer request form. Field names mirror `bookingSchema`
 * (direction/rentalType, date+time/pickupDate+pickupTime, location/
 * pickupLocation, passengers, luggage, flightNumber) so the payload can be
 * handed to the Booking system later without reshaping it.
 *
 * Airport availability is validated against the configured
 * `AIRPORT_OPTIONS` list, so disabled airports can never be submitted.
 */
export const airportTransferSchema = z.object({
  airport: z.string().min(1, 'Please select an airport'),
  direction: z.enum(['ARRIVAL', 'DEPARTURE'], {
    required_error: 'Please select arrival or departure',
    invalid_type_error: 'Please select arrival or departure',
  }),
  date: z.string().min(1, 'Date is required'),
  time: z.string().min(1, 'Time is required'),
  flightNumber: z
    .string()
    .max(12, 'Flight number is too long')
    .regex(/^[A-Za-z0-9 -]+$/, 'Use letters and numbers only')
    .optional()
    .or(z.literal('')),
  location: z
    .string()
    .trim()
    .min(5, 'Enter the pickup or drop-off location')
    .max(200),
  passengers: z.coerce
    .number()
    .min(1, 'At least 1 passenger')
    .max(50, 'Maximum 50 passengers — contact us for larger groups'),
  luggage: z.coerce
    .number()
    .min(0, 'Luggage cannot be negative')
    .max(20, 'Maximum 20 pieces'),
  vehiclePreference: z.enum(VEHICLE_PREFERENCE_VALUES, {
    required_error: 'Please select a vehicle preference',
    invalid_type_error: 'Please select a vehicle preference',
  }),
  customerName: z.string().trim().min(2, 'Name must be at least 2 characters').max(100),
  whatsapp: z
    .string()
    .trim()
    .min(1, 'WhatsApp number is required')
    .refine((value) => {
      const digits = value.replace(/\D/g, '');
      return digits.length >= 10 && digits.length <= 15;
    }, 'Enter a valid WhatsApp number (e.g., +92 3XX XXXXXXX)'),
  honeypot: z.string().optional(),
})
  .superRefine((data, ctx) => {
    if (!data.airport) return;
    const allowed = getEnabledAirportIds();
    if (ALLOW_OTHER_AIRPORT) allowed.push(OTHER_AIRPORT_ID);
    if (!allowed.includes(data.airport)) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['airport'],
        message: 'Please select a valid airport',
      });
    }
  })
  .refine((data) => !data.date || DATE_PATTERN.test(data.date), {
    message: 'Enter a valid date',
    path: ['date'],
  })
  .refine((data) => !data.time || TIME_PATTERN.test(data.time), {
    message: 'Enter a valid time (HH:MM)',
    path: ['time'],
  })
  .refine((data) => {
    if (!DATE_PATTERN.test(data.date) || !TIME_PATTERN.test(data.time)) return true;
    const transferAt = new Date(`${data.date}T${data.time}`);
    // 12-hour grace so server/client timezone differences never reject a
    // genuinely upcoming transfer; clearly past dates are still rejected.
    return transferAt.getTime() > Date.now() - 12 * 60 * 60 * 1000;
  }, {
    message: 'Transfer date and time must be in the future',
    path: ['date'],
  })
  .refine((data) => !data.honeypot, {
    message: 'Spam detected',
    path: ['honeypot'],
  });

/**
 * Image fields must accept an empty string (react-hook-form sends '' for an
 * untouched optional input) and site paths like /vehicles/car.jpg, which the
 * admin placeholders document. Empty input is normalised to null so it is
 * never stored as ''.
 */
const imageSource = z
  .string()
  .trim()
  .refine(
    (value) => value.startsWith('/') || /^https?:\/\//.test(value),
    'Image must be a site path (/...) or an http(s) URL'
  );

const optionalImageSource = z
  .string()
  .trim()
  .refine(
    (value) => value === '' || value.startsWith('/') || /^https?:\/\//.test(value),
    'Image must be empty, a site path (/...) or an http(s) URL'
  )
  .optional()
  .nullable()
  .transform((value) => (value === '' ? null : value));

export const vehicleSchema = z.object({
  name: z.string().min(2, 'Name must be at least 2 characters').max(100),
  brand: z.string().min(1, 'Brand is required').max(50),
  model: z.string().min(1, 'Model is required').max(50),
  year: z.coerce.number().min(1990).max(new Date().getFullYear() + 1),
  category: z.enum(['ECONOMY', 'SEDAN', 'SUV', 'LUXURY', 'VAN', 'MINIBUS', 'COASTER', 'HIGHLACE', 'PICKUP']),
  transmission: z.enum(['MANUAL', 'AUTOMATIC']),
  fuelType: z.enum(['PETROL', 'DIESEL', 'HYBRID', 'ELECTRIC', 'CNG']),
  seats: z.coerce.number().min(1).max(50),
  doors: z.coerce.number().min(2).max(6),
  luggageCapacity: z.coerce.number().min(0).max(20),
  dailyRate: z.coerce.number().min(0),
  weeklyRate: z.coerce.number().min(0).optional().nullable(),
  monthlyRate: z.coerce.number().min(0).optional().nullable(),
  description: z.string().min(10, 'Description must be at least 10 characters').max(5000),
  features: z.array(z.string()).default([]),
  images: z.array(imageSource).default([]),
  thumbnail: optionalImageSource,
  isAvailable: z.boolean().default(true),
  isFeatured: z.boolean().default(false),
  location: z.string().default('Islamabad'),
  mileage: z.coerce.number().min(0).default(0),
  licensePlate: z.string().min(1, 'License plate is required').max(20),
  ac: z.boolean().default(true),
  selfDriveAvailable: z.boolean().default(true),
  chauffeurAvailable: z.boolean().default(true),
  unlimitedKilometers: z.boolean().default(false),
  kilometerLimit: z.coerce.number().int().min(0).optional().nullable(),
});

export const adminLoginSchema = z.object({
  email: z.string().email('Invalid email address'),
  password: z.string().min(1, 'Password is required'),
});

export const adminUserSchema = z.object({
  name: z.string().min(2, 'Name must be at least 2 characters').max(100),
  email: z.string().email('Invalid email address'),
  password: z.string().min(8, 'Password must be at least 8 characters').optional().or(z.literal('')),
  role: z.enum(['ADMIN', 'STAFF']),
  phone: z.string().max(20).optional().or(z.literal('')),
  city: z.string().max(100).optional().or(z.literal('')),
});

export const settingSchema = z.object({
  key: z.string().min(1, 'Key is required').max(100),
  value: z.string(),
  type: z.enum(['STRING', 'NUMBER', 'BOOLEAN', 'JSON', 'TEXT']).default('STRING'),
  group: z.string().min(1, 'Group is required').max(50),
  label: z.string().min(1, 'Label is required').max(100),
  description: z.string().max(500).optional().nullable(),
  isPublic: z.boolean().default(false),
});

/** A single settings key accepted from admin input. */
export const settingKeySchema = z
  .string()
  .regex(/^[a-z0-9_-]{1,64}$/, 'Invalid setting key');

/**
 * Server-side validation for settings updates. Never trust the client:
 * keys must match the known key shape (no prototype tricks), values are
 * bounded, and URL-like keys may only hold safe link values - some
 * settings are rendered straight into `href` attributes on public pages,
 * so `javascript:` and similar schemes must never be stored.
 */
export const settingsUpdateSchema = z
  .record(settingKeySchema, z.string().max(50000, 'Setting value is too long'))
  .refine(
    (record) =>
      Object.entries(record).every(
        ([key, value]) =>
          !/(url|image|photo)/.test(key) ||
          value === '' ||
          /^(https?:\/\/|\/|#|mailto:|tel:)/.test(value)
      ),
    { message: 'Link settings must start with https://, http://, /, #, mailto: or tel:' }
  );

export const serviceSchema = z.object({
  name: z.string().min(2, 'Name must be at least 2 characters').max(100),
  slug: z.string().min(2, 'Slug must be at least 2 characters').max(100).regex(/^[a-z0-9-]+$/, 'Slug can only contain lowercase letters, numbers, and hyphens'),
  description: z.string().min(10, 'Description must be at least 10 characters').max(5000),
  image: optionalImageSource,
  active: z.boolean().default(true),
  icon: z.string().regex(/^[a-z0-9-]+$/, 'Icon can only contain lowercase letters, numbers, and hyphens').max(30).default('car'),
  href: z.string().regex(/^\/[a-z0-9\-/]*$/, 'Link must start with / and contain only lowercase letters, numbers, hyphens or slashes').max(200).default('/'),
  order: z.coerce.number().min(0).max(10000).default(0),
  features: z
    .array(
      z.object({
        title: z.string().min(2, 'Feature title must be at least 2 characters').max(100),
        description: z.string().min(10, 'Feature description must be at least 10 characters').max(500),
      })
    )
    .max(12, 'A service can have at most 12 features')
    .default([]),
});

export const blogPostSchema = z.object({
  title: z.string().trim().min(3, 'Title must be at least 3 characters').max(200),
  slug: z
    .string()
    .trim()
    .min(3, 'Slug must be at least 3 characters')
    .max(200)
    .regex(/^[a-z0-9-]+$/, 'Slug can only contain lowercase letters, numbers, and hyphens'),
  excerpt: z.string().trim().min(10, 'Excerpt must be at least 10 characters').max(500),
  content: z.string().trim().min(20, 'Content must be at least 20 characters').max(100000),
  featuredImage: z
    .string()
    .trim()
    .max(500)
    .refine(
      (v) => v === '' || v.startsWith('/') || /^https?:\/\//.test(v),
      'Featured image must be a site path (/...) or an http(s) URL'
    ),
  category: z.string().trim().min(1, 'Category is required').max(100),
  tags: z.array(z.string().trim().min(1).max(50)).max(10).default([]),
  seoTitle: z.string().trim().max(70, 'SEO title should be 70 characters or fewer').optional().or(z.literal('')),
  seoDescription: z
    .string()
    .trim()
    .max(170, 'SEO description should be 170 characters or fewer')
    .optional()
    .or(z.literal('')),
  isPublished: z.boolean().default(false),
});

export type BlogPostInput = z.infer<typeof blogPostSchema>;

export const faqSchema = z.object({
  question: z.string().min(5, 'Question must be at least 5 characters').max(500),
  answer: z.string().min(10, 'Answer must be at least 10 characters').max(5000),
  category: z.string().min(1, 'Category is required').max(100),
  order: z.coerce.number().min(0).default(0),
  isActive: z.boolean().default(true),
});

export const testimonialSchema = z.object({
  name: z.string().min(2, 'Name must be at least 2 characters').max(100),
  role: z.string().max(100).optional().nullable(),
  company: z.string().max(100).optional().nullable(),
  avatar: z.string().url().optional().nullable(),
  content: z.string().min(10, 'Content must be at least 10 characters').max(2000),
  rating: z.coerce.number().min(1).max(5).default(5),
  isVerified: z.boolean().default(false),
  isActive: z.boolean().default(true),
  order: z.coerce.number().min(0).default(0),
});

export const locationSchema = z.object({
  name: z.string().min(2, 'Name must be at least 2 characters').max(100),
  slug: z.string().min(2, 'Slug must be at least 2 characters').max(100).regex(/^[a-z0-9-]+$/, 'Slug can only contain lowercase letters, numbers, and hyphens'),
  city: z.string().min(1, 'City is required').max(100),
  address: z.string().min(5, 'Address must be at least 5 characters').max(500),
  phone: z.string().max(20).optional().nullable(),
  email: z.string().email().optional().nullable(),
  latitude: z.coerce.number().optional().nullable(),
  longitude: z.coerce.number().optional().nullable(),
  isActive: z.boolean().default(true),
  order: z.coerce.number().min(0).default(0),
});

export const basePromotionSchema = z.object({
  code: z.string().min(2, 'Code must be at least 2 characters').max(50).toUpperCase(),
  title: z.string().min(2, 'Title must be at least 2 characters').max(100),
  description: z.string().min(10, 'Description must be at least 10 characters').max(1000),
  discountType: z.enum(['PERCENTAGE', 'FIXED_AMOUNT']),
  discountValue: z.coerce.number().min(0),
  minAmount: z.coerce.number().min(0).optional().nullable(),
  maxDiscount: z.coerce.number().min(0).optional().nullable(),
  startDate: z.string().min(1, 'Start date is required'),
  endDate: z.string().min(1, 'End date is required'),
  usageLimit: z.coerce.number().min(1).optional().nullable(),
  isActive: z.boolean().default(true),
  applicableCategories: z.array(z.enum(['ECONOMY', 'SEDAN', 'SUV', 'LUXURY', 'VAN', 'MINIBUS', 'COASTER', 'HIGHLACE', 'PICKUP'])).default([]),
});

export const promotionSchema = basePromotionSchema.refine((data) => new Date(data.endDate) > new Date(data.startDate), {
  message: 'End date must be after start date',
  path: ['endDate'],
});

export type BookingInput = z.infer<typeof bookingSchema>;
export type ContactInput = z.infer<typeof contactSchema>;
export type InquiryInput = z.infer<typeof inquirySchema>;
export type AirportTransferInput = z.infer<typeof airportTransferSchema>;
export type VehicleInput = z.infer<typeof vehicleSchema>;
export type AdminLoginInput = z.infer<typeof adminLoginSchema>;
export type AdminUserInput = z.infer<typeof adminUserSchema>;
export type SettingInput = z.infer<typeof settingSchema>;
export type ServiceInput = z.infer<typeof serviceSchema>;
export type FAQInput = z.infer<typeof faqSchema>;
export type TestimonialInput = z.infer<typeof testimonialSchema>;
export type LocationInput = z.infer<typeof locationSchema>;
export type PromotionInput = z.infer<typeof promotionSchema>;